### ISSUE TITLE
1. Написание технического задания

### ISSUE THREAD

**Issue by Naint** [Naint/CourseWorkDataBase#2]

**Comment by Naint** [comment]
[ТЗ_Курсач_ЬД.docx](https://github.com/Naint/CourseWorkDataBase/files/9667844/_._.docx)

**Comment by Naint** [comment]
Техническое задание на разработку информационной системы “Прокат автомобилей”
Назначение разработки системы
Требуется разработать Android приложение для аренды автомобилей. Создать функционал управления бизнес-процессом аренды автомобилей, сопроводительной деятельности компании.

Общие положения
Система должна состоять из следующих программных компонентов:
1.	Личный кабинет.
a.	Личный кабинет клиента.
b.	Личный кабинет администратора.
2.	Каталог актуальных моделей для заключения договора аренды.
3.	Список пунктов выдачи автомобилей(стоянок). (считается, что все автомобили доставляются на определенные стоянки)
4.	Форма для регистрации/авторизации

	Интерфейс приложения
Оформление мобильного приложения должно соответствовать нативному стилю ОС Android. Жесткие требования по оформлению не предъявляются. Язык интерфейса приложения – Русский.	
	
Составные элементы приложения:
•	Главная страница (навигационное меню с переходами в необходимые подразделы)
•	Профиль (страница, содержащая информацию о пользователе, баланс)
•	Текущие бронирования (страница, отображающая текущие забронированные автомобили)
•	История бронирований
•	Каталог доступных для бронирования автомобилей
•	Акции и спецпредложения

Интерфейс системы управления
Пользователи разделяются на несколько ролей:
1.	Администратор
2.	Клиент
3.	Автомеханик

Расширенный доступ к системе управления приложением имеют 2 роли: администратор и автомеханик.
Доступный функционал для роли Администратор:
•	Добавление новых автомобилей
•	Редактирование информации об автомобилях
•	Удаление автомобилей из каталога
•	Блокировка/разблокировка пользователей
•	Редактирование информации о стоянках
Доступный функционал для роли Автомеханик:
•	Сокрытие автомобиля из каталога в целях отправления на плановое ТО/ремонта после ДТП
•	Установка даты планового ТО для автомобилей
•	Редактирование информации об автомобилях
Для роли “Пользователь” предусмотрен стандартный набор функций (не имеет расширенного доступа)

Набор сущностей информационной системы
Информационная система должна содержать сущности:
1.	Автомобили (содержит информацию об автомобиле: состояние, пробег, год выпуска, количество мест, класс, марка, объём бака, доп. оборудование, дата проведения ТО)
2.	Пользователи (содержит информацию о пользователях: ФИО, дата рождения, серия и номер паспорта, номер В/У, ID, город, номер телефона, логин, пароль)
3.	Акты приёма передачи(содержит информацию о принятом/переданном автомобиле: состояние салона, состояние кузова, замечания, количество бензина в баке, наличие доп.оборудования)
4.	Стоянки (содержит информацию о стоянках: количество мест, заполненность, график работы, номер ответственного за стоянку)

Системные требования
Мобильное приложение должно быть совместимо с устройствами на Android 6.0 и выше. Для корректного отображения компонентов программы требуется устройством с разрешением экрана 1280x720 и выше.

**Comment by wldmr-key** [comment]
нет-нет-нет
все-таки следует написать ТЗ поближе к ГОСТ ))

**Comment by wldmr-key** [comment]
твой скорбный труд не пропадет - написанное тобой частично войдет в ТЗ, частично в другие разделы пояснительной записки, но ТЗ все-таки необходимо ))

**Comment by Naint** [comment]
1.	Техническое задание
1.1.	Общие сведения:
1.1.1.	 Полное наименование системы:
Данное техническое задание регулирует разработку системы “Прокат авто”.

1.1.2.	 Наименования организации-заказчика, разработчика системы:
Система разрабатывается студентом группы ИУК5-51Б КФ МГТУ имени Баумана Долматовым Владиславом.

1.1.3.	Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ – 01 сентября 2022 года.
Плановый срок окончания работ – 25 декабря 2022 года.

1.1.4.	 Определения, обозначения и сокращения:
	МО – мобильное устройство
	ОС – Операционная система
	ТЗ – Техническое задание
	СУБД – Система управления базами данных
1.1.5.	Порядок оформления и предъявление заказчику результатов работ по созданию системы:
Организованы еженедельные консультации с заказчиком для демонстрации промежуточных результатов работы, обсуждения предметной области, выявления и решения промежуточных проблем.




1.2.	Назначение и цели создания системы
1.2.1.	Назначение системы:
Система предназначена для предоставления возможностей по бронированию автомобилей для использования их в интересах пользователей.
1.2.2.	 Цели создания системы:	
Информационная система создается со следующими целями:
•	Повышение удобства пользования арендой автомобилей
•	Реализация постоянно технической поддержки пользователей
•	Обеспечения сбора и обработки информации в целях улучшения качества работы компании 

1.3.	 Требования к системе
1.3.1.	 Требования к системе в целом:
1.	Требования к структуре и функционированию системы:
Система представляет собой на операционной системе Android. Программа должна понятный графический интерфейс.
Основные функции системы со стороны пользователя:
	Возможность бронирования автомобиля
	Возможность просмотра истории аренд(заказов)
	Возможность отмены бронирования автомобиля
	Возможность обращения в службу технической поддержки

Основные функции системы со стороны администратора:
	Возможность просмотра списка всех пользователей
	Возможность блокировки пользователей
	Возможность редактирования информации о пользователях
	Возможность добавления новых автомобилей
	Возможность редактирования информации о текущих автомобилях в приложении

2.	Требования к численности и квалификации персонала системы и режиму его работы:
Программа рассчитана для работы 1 пользователя. Пользователь должен обладать минимальными навыками работы со смартфоном на базе ОС Android 6.0 и выше.
3.	Требования к надежности:
В случае выхода из строя части системы или всей системы в целом, общая работоспособность ПК должна сохраниться.
 	Программа не должна прекращать работу, если это не требуется специалисту или не предусмотрено сценарием использования программы.
4.	Требования по эргономике и технической эстетике:
Графический интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых неочевидно или элементы, функционал которых отсутствует или не соответствует пояснению в конструкторской документации или непосредственно в интерфейсе, должен быть понятен и не перегружен графическими элементами.

5.	Требования по сохранности информации при авариях:
При сбоях в работе смартфона программа закончит работу с потерей несохраненных данных. 
После ликвидации сбоя смартфона операционная система должна обеспечить функционирование приложения в нормальном режиме.





6.	Требования по стандартизации и унификации:
Проектное решение рекомендуется разрабатывать с применением стандартизированных паттернов проектирования программных систем.
1.3.2.	 Требования к функциям (задачам), выполняемым системой:
	Просмотр списка доступных для бронирования авто
	Бронирование автомобиля 
	Просмотр истории бронирований
	Заполнение персональной информации
1.3.3.	 Требования к видам обеспечения
1.	Требования информационному обеспечению системы:
Система должна получать из БД информацию об автомобилях, пользователях.

2.	Требования к лингвистическому обеспечению системы:
В качестве языка программирования для разработки в системе используется Java.
	Средством описания предметной области является русский язык.
	Средством взаимодействия пользователя с системой является русский язык.
3.	Требования к программному обеспечению системы:
Операционная система Android 7.0 и выше.


1.4	 Порядок контроля и приемки системы
Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность.
Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.

1.5	 Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
Для корректной работы системы, на ПК должны быть установлена Android 6.0 и выше. Для использования программы необходимо запустить исполняемый файл.

**Comment by wldmr-key** [comment]
все это очень мило, но как-то из ТЗ не очевидно, что хоть какие-то базы данных и серверы в системе наличествуют

**Comment by Naint** [comment]
1.	Техническое задание
1.1. Общие сведения

1.1.1. Полное наименование системы

Мобильное приложение для аренды автомобилей

1.1.2. Наименование организации-заказчика, разработчика системы.

Исполнителем проекта является студент Калужского филиала МГТУ им. Н.Э. Баумана, факультета "Информатика и управление", кафедры ИУК5 "Системы обработки информации", группы ИУК5-51Б, Долматов Владислав Денисович.
Заказчиком является индивидуальный предприниматель N.

1.1.3. Плановые сроки начала и окончания работы по созданию системы

Систему необходимо разработать в период с 01.09.2022 по 31.11.2022

1.2. Назначение и цели создания системы

1.2.1. Назначение системы

Интернет-магазин предназначен для лиц/компаний, которым требуется арендовать транспортное средство на определенное время.





1.2.2. Цели создания системы

Целью создания мобильного приложения является замена зарубежных аналогов, увеличение прибыли компании за счёт увеличения клиентской базы.

1.3. Характеристика объектов по созданию системы.

Пользователь выбирает понравившийся автомобиль из предложенного каталога товаров и бронирует его. Перед бронированием обязательно нужно выполнить авторизацию в систему и указать все необходимые данные. Если данные соответствуют требованиям, то автомобиль бронируется за ним, в случае отказа можно обратиться в службу технической поддержки для решения ситуации.

1.4. Требования к системе.

1.4.1. Требования к структуре и функционированию системы.

Система представляет из себя несколько модулей:

- клиентская часть, где клиенты смогут посмотреть информацию о компании, ознакомиться со списком автомобилей, ценами на аренду, сроками аренды, зарегистрироваться и оформить бронирование.

- администраторская часть, где администраторы смогут добавлять автомобили и категории, а также просматривать информацию о бронированиях/пользователях.




Создаваемая система должна реализовывать следующие функции:

 - Система должна предоставлять заказчику страницу выбора автомобиля с сортировкой по категориям и типам.

 - Пользователь может регистрироваться в системе (а также авторизовываться после регистрации)

 - Пользователь может оформлять бронирование

У администраторов должна быть возможность:

 - Добавлять/Изменять информацию об автомобиле

 - Добавлять/Изменять информация о стоянках

 - Добавлять/Изменять контракты

1.4.2. Требования к численности и квалификации персонала системы и режиму его работы.

Система рассчитана на неограниченное количество пользователей со стороны клиентской части, и нескольких администраторов.

 
1.5. Состав и содержание работ по созданию системы.

- Анализ требований к системе:
Разработчик должен выполнить анализ области применения разрабатываемой системы с точки зрения определения требований к ней.

- Проектирование программной архитектуры:
Разработчик должен определить программную архитектуру, которая описывает общую структуру объекта и определяет компоненты программного объекта.

- Программирование и тестирование программных средств:
Разработчик должен разработать каждый программный модуль и базу данных, а также процедуры испытаний (тестирования) и данные для тестирования каждого программного модуля и базы данных.

1.6. Порядок контроля и приемки системы.

Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность. Все создаваемые программные решения передаются заказчику как в виде готовых модулей, так и в виде исходных кодов, представляемых в электронной форме.

Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.
 
1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие.

Для корректной работы системы на смартфоне должен быть доступ в интернет, установлена Android 6.0 и выше.

1.8. Требования к документированию.

Требуется предоставить:
- Техническое задание в соответствии с ГОСТ 34.602-809
- Расчётно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
пойдет
