### ISSUE TITLE
2. Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by Naint** [Naint/CourseWorkDataBase#3]

**Comment by Naint** [comment]
Описание предметной области:

В данном курсовом проекте была описана деятельность интернет-магазина по аренде автомобилей. Мобильное приложение позволяет пользователям прямо со своего устройства выбрать понравившийся автомобиль, забронировать его, выбрать способ получения(одна из стоянок). Управление мобильным приложением – процесс планирования, координации и контроля бизнес-процессов. Администратор является главным звеном в бизнес-процессе, который должен поддерживать актуальную базу данных о наличии товара, для большего спроса клиентов.

В созданном мною мобильном приложении существует 2 роли: арендатор(простой пользователь) и администратор.

У арендатора есть возможно выбора автомобиля из каталога. Упрощает выбор сортировка по категориям и типам самих автомобилей. Под категориями подразумевается, какие виды  категории прав имеются(A, B, C, D, E и тд), а под типами – какие типы автомобилей имеются(внедорожник, седан, хетчбек и тд)

Также имеется информация о недочетах в автомобиле, где могут быть указаны различные потёртости, царапины, вмятины, прокуренности в салоне.
Пользователь выбирает автомобиль и пробует его забронировать. Для возможности забронировать автомобиль пользователь должен быть авторизован в системе и все необходимые данные должно быть заполнены. 
После бронирования автомобиля его меняется на “Забронирован” и другие пользователи не видят данный автомобиль в списке доступных для бронирования. Со стороны пользователя автомобиль помещается в раздел “Мои бронирования”, где и остается даже после окончания аренды автомобиля.

**Comment by Naint** [comment]
Требования:

1.4. Требования к системе.

1.4.1. Требования к структуре и функционированию системы.

Система представляет из себя несколько модулей:

- клиентская часть, где клиенты смогут посмотреть информацию о компании, ознакомиться со списком автомобилей, ценами на аренду, сроками аренды, зарегистрироваться и оформить бронирование.

- администраторская часть, где администраторы смогут добавлять автомобили и категории, а также просматривать информацию о бронированиях/пользователях.




Создаваемая система должна реализовывать следующие функции:

 - Система должна предоставлять заказчику страницу выбора автомобиля с сортировкой по категориям и типам.

 - Пользователь может регистрироваться в системе (а также авторизовываться после регистрации)

 - Пользователь может оформлять бронирование

У администраторов должна быть возможность:

 - Добавлять/Изменять информацию об автомобиле

 - Добавлять/Изменять информация о стоянках

 - Добавлять/Изменять контракты

1.4.2. Требования к численности и квалификации персонала системы и режиму его работы.

Система рассчитана на неограниченное количество пользователей со стороны клиентской части, и нескольких администраторов.

**Comment by wldmr-key** [comment]
"В данном курсовом проекте была описана", "В созданном мною мобильном приложении" - приведи в порядок стиль изложения. В этом пункте должно быть описание предметой области

Описание предметной области - как происходит аренда автомобилей - основные понятия

Требования к системе - основные функции и понятия разрабатываемой системы

**Comment by Naint** [comment]
В качестве предметной области выбрано мобильное приложение для аренды автомобилей. Мобильное приложение позволяет пользователям прямо со своего мобильного устройства выбрать понравившийся автомобиль, забронировать его, выбрать способ получения(одна из стоянок). Администратор является главным звеном в бизнес-процессе, который должен поддерживать актуальную базу данных о наличии автомобилей, для большего спроса клиентов. 
Процесс аренды автомобиля начинается с регистрации пользователя в приложении и заполнения всех необходимых данных, затем перед пользователем открывается возможность арендовать понравившийся ему автомобиль по определенным ценам. При подаче заявки на бронирование автомобиля отправляется запрос в базу данных на проверку статуса(занят/не занят), после чего автомобиль либо бронируется за пользователем, либо приходит оповещение о том, что автомобиль уже кто-то забронировал. После завершения аренды автомобиля в разделе “Мои бронирования” появляется соответствующее поле с информацией о бронировании.

**Comment by Naint** [comment]
2.5. Требования к системе

•	Система должна предоставлять арендатору страницу выбора автомобиля с сортировкой по категориям.
•	Пользователь может регистрироваться в системе (а также авторизовываться после регистрации)
•	Пользователь должен иметь возможность оформления аренды
У администратора должна быть возможность:
•	Добавлять/Изменять/удалять автомобили
•	Добавлять/Изменять/удалять стоянки
•	Добавлять/Изменять/Удалять контракты

**Comment by Naint** [comment]
Описание предметной области:

Программа помогает пользователям бронировать автомобиль. Изначально администратор создает стоянку/стоянки с указанием типа стоянки, вместимость и адреса. Затем администратор может добавить автомобиль, который будет располагаться на одной из созданных стоянок, об автомобили заносится следующая информация: ID, марка, модель, регистрационный номер, год выпуска, пробег, цвет, состояние, ID парковки. 
 После чего пользователи регистрируются и могут начать использовать сервис, пользователь бронирует один из автомобилей и заключает контракт на его аренду. В случае попадания автомобиля в ДТП заносится необходимая информация в таблицу, информация о ДТП завязано на каждом автомобиле.

**Comment by wldmr-key** [comment]
Описание предметной области - как происходит аренда автомобилей - основные понятия

я уже это писал и ты исправлялся. Ты вновь за старое? Напиши окончательный вариант описания предметной области и требований к системе. Если тебе очень хочется в концептуальной схеме использовать названия атрибутов и сущностей на английском языке - будь последователен - пиши и описание на английском

**Comment by wldmr-key** [comment]
Еще раз
Описание предметной области - как происходит аренда автомобилей - основные понятия. Приложения еще нет. А у тебя там слова: "администратор добавляет в приложение", "у пользователя открывается возможность", "отправляется запрос в базу данных"  и т.д. Создается такое впечатление, что до тебя никто автомобилей не арендовал

**Comment by Naint** [comment]
В качестве предметной области выбрана аренда автомобилей. На данный момент существуют сайты, которые обеспечивают такой процесс, но весь процесс там проводится через оператора, данный процесс можно автоматизировать. Пользователь заполняет все необходимые данные, регистрируется в системе. После чего он может забронировать любой понравившийся ему автомобиль на определенных условиях. Условия содержатся в контракте, которые подписывается при заключении договора аренды автомобиля на определенный срок.  После чего забрать автомобиль с одной из стоянок. При попадании арендатора в ДТП соответствующая информация должна быть занесена в систему.

2.5. Требования к системе

• Система должна предоставлять арендатору страницу выбора автомобиля с сортировкой по категориям.
• Пользователь может регистрироваться в системе (а также авторизовываться после регистрации)
• Пользователь должен иметь возможность оформления аренды
У администратора должна быть возможность:
• Добавлять/удалять информацию об автомобилях
• Добавлять/удалять информацию о стоянках
• Добавлять/Удалять информацию о контрактах
