### ISSUE TITLE
4. Создать концептуальную схему данных предметной области (предварительную, конечно)

### ISSUE THREAD

**Issue by Naint** [Naint/CourseWorkDataBase#5]

**Comment by Naint** [comment]
![Снимок экрана (847)](https://user-images.githubusercontent.com/60396802/225833001-f1fd9879-43cf-427d-a140-2120e0e19732.png)

**Comment by wldmr-key** [comment]
это не концептуальная схема. Что за id и FK. Для чего нужна концептуальная схема?! Что за странная нотация? что означают стрелки?

**Comment by Naint** [comment]
![Концептуальная схема drawio](https://user-images.githubusercontent.com/60396802/227316198-ce2107fc-34bb-4e83-9d3e-f4d907762f22.png)
![Логическая модель](https://user-images.githubusercontent.com/60396802/227316206-b69f8ee0-295a-4998-b16c-48a85b7ca8a8.jpg)

**Comment by wldmr-key** [comment]
Нотация остается странной. Если это нотация Чена, то связи сущностей с атрибутами рисуются по-другому. Очень простой критерий правильности концептуальной схемы - все написанные на ней слова должны встречаться в описании предметной области и требованиях к системе. У тебя это не так

**Comment by Naint** [comment]
![Концептуальная схема drawio](https://user-images.githubusercontent.com/60396802/227621917-923a386a-d1f8-4b63-bbdc-18b7ddbeb267.png)

Описание предметной области поправил, схему немного тоже

**Comment by Naint** [comment]
![diagpng](https://user-images.githubusercontent.com/60396802/227903211-7f301bbd-7324-4a50-8d5f-d84ca8f42d58.jpg)

**Comment by Naint** [comment]
![diag](https://user-images.githubusercontent.com/60396802/228129455-21162fce-0a2f-4aa3-80e0-75e0df45ff93.jpg)

Да, согласен, связь автомобили-пользователи-контракты смотрится лишней, оставил связь пользователи-контракты.

**Comment by wldmr-key** [comment]
не угадал
За тобой следующая попытка

**Comment by wldmr-key** [comment]
опять нет. Вариантов немного осталось

**Comment by Naint** [comment]
![draw_v3](https://user-images.githubusercontent.com/60396802/228341729-4faf3b5d-8aca-4e3d-a695-232a685e23c1.png)

А посмотрите, пожалуйста, еще раз
Может, так?

**Comment by wldmr-key** [comment]
неа

**Comment by Naint** [comment]
![draw_v4](https://user-images.githubusercontent.com/60396802/228428416-6cdfe4e9-e82b-4f0e-8b11-29ce37e7472e.png)

Кажется, это последний вариант, атрибуты тут не дублируют связи

**Comment by wldmr-key** [comment]
нет - вернись к исходной схеме с кольцом и вновь подумай

**Comment by Naint** [comment]
![drawio](https://user-images.githubusercontent.com/60396802/228581046-56cea7b8-9381-4efc-9530-2874cefe4e13.png)

Атрибуты лишние убрал
По связи пользователь-контракт-автомобиль теперь так:

Пользователь заключает контракт, по которому бронируется автомобиль.

**Comment by wldmr-key** [comment]
> Атрибуты лишние убрал

ну-ну... Нашел номер контракта в ДТП. Дальше искать не стал...

> По связи пользователь-контракт-автомобиль теперь так:

наконец-то

**Comment by wldmr-key** [comment]
сойдет

**Comment by Naint** [comment]
В ЭОС тогда заливаю по частям все? Или еще что-то нужно?

**Comment by wldmr-key** [comment]
у меня рука не поднимается поставить тебе  положительную оценку, поэтому, я отписал Евгению Владимировичу, чтобы он сделал это ))
Загружай все барахло в ЭОС, включая презентацию и графические материалы. Распечатывай и подходи к Евгению Владимировичу с направлением
За руководителя я в понедельник распишусь
